apiVersion: v1
kind: Service
metadata:
  name: beer-catalogue-api
  labels:
    app: beer-catalogue-api
spec:
  type: ClusterIP
  selector:
    app: beer-catalogue-api
  ports:
    - port: 8080
      targetPort: 8080
